# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bitreverse.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(11, 11, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.PB_readsource = QtWidgets.QPushButton(self.frame)
        self.PB_readsource.setObjectName("PB_readsource")
        self.verticalLayout.addWidget(self.PB_readsource)
        self.PB_savetarget = QtWidgets.QPushButton(self.frame)
        self.PB_savetarget.setObjectName("PB_savetarget")
        self.verticalLayout.addWidget(self.PB_savetarget)
        self.CB_bitreverse = QtWidgets.QCheckBox(self.frame)
        self.CB_bitreverse.setObjectName("CB_bitreverse")
        self.verticalLayout.addWidget(self.CB_bitreverse)
        self.CB_bytereverse = QtWidgets.QCheckBox(self.frame)
        self.CB_bytereverse.setObjectName("CB_bytereverse")
        self.verticalLayout.addWidget(self.CB_bytereverse)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.frame)
        self.TE_source = QtWidgets.QTextEdit(self.widget)
        self.TE_source.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.TE_source.setObjectName("TE_source")
        self.horizontalLayout.addWidget(self.TE_source)
        self.frame_3 = QtWidgets.QFrame(self.widget)
        self.frame_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.PB_leftturn = QtWidgets.QPushButton(self.frame_3)
        self.PB_leftturn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.PB_leftturn.setObjectName("PB_leftturn")
        self.verticalLayout_3.addWidget(self.PB_leftturn)
        self.PB_rightturn = QtWidgets.QPushButton(self.frame_3)
        self.PB_rightturn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.PB_rightturn.setObjectName("PB_rightturn")
        self.verticalLayout_3.addWidget(self.PB_rightturn)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout.addWidget(self.frame_3)
        self.TE_target = QtWidgets.QTextEdit(self.widget)
        self.TE_target.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.TE_target.setObjectName("TE_target")
        self.horizontalLayout.addWidget(self.TE_target)
        self.verticalLayout_4.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bit Reverse"))
        self.PB_readsource.setText(_translate("MainWindow", "ReadSource"))
        self.PB_savetarget.setText(_translate("MainWindow", "SaveTarget"))
        self.CB_bitreverse.setText(_translate("MainWindow", "Bit  Rev"))
        self.CB_bytereverse.setText(_translate("MainWindow", "Byte Rev"))
        self.PB_leftturn.setText(_translate("MainWindow", ">>"))
        self.PB_rightturn.setText(_translate("MainWindow", "<<"))

